### ISSUE TITLE
EC-Rest plugin 

### ISSUE THREAD

**Issue by borodark** [electric-cloud/EC-Support#11]
Error running POST Request to Hipchat API:
Curl command is able to post message into chat room

> curl --header "content-type: application/json" --header "Authorization: Bearer <SEE ME FOR A KEY>" -X POST -d '{"message":"The message from build &_"}' 
> https://api.hipchat.com/v2/room/2352617/message

Here is the link to error in our EC instanse: 
https://ec/commander/link/jobDetails/jobs/963def3e-c086-11e5-9deb-005056af66bd?tabGroup=parameterTableHeader&s=Jobs

Here is report in EC console:

Job: EC-Rest_runRest_4_20160121163318
Workspace File  /   createRestRequest.9649d627-c086-11e5-bebc-005056af66bd.log

More
Using plugin EC-Rest version 1.0.7.83293
Loading config HipChatAPITest
Creating Request...

> Request:
> POST https://api.hipchat.com/v2/room/2352617/message
> Authorization: [PROTECTED]
> Content-Type: application/json

{"message":"The message from build &_"}
Sending Request to Server...
_----------------------------------------------------------------------------------------------------_
Response Received.
Checking for errors...

Status: 500 Connect failed: connect: Unknown error; Unknown error
ERROR! The server was unable to fulfil the request.
Please check your parameters.

**Comment by lrochette** [comment]
This is not an EC-Support plugin issue
A ticket has been opened with Electric Cloud support
